<a href="https://colab.research.google.com/github/diaJalaeyRakhna/numpy-assigns/blob/main/NumpyVsPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list=range(1000000)

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(1000000)

In [ ]:
%time for i in range(1,10): r=[x*2 for x in list]

Wall time: 1.38 s


In [ ]:
%time for i in range(1,10): r=arr*2

Wall time: 359 ms


In [ ]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones((3,15))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.empty((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
list=[1,3,5,7]
np.array(list)

array([1, 3, 5, 7])

In [ ]:
x=np.arange(10, 100, 10) #start, end (exclusive), step
x

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(x.shape, x.ndim, x.dtype)

(9,) 1 int32


In [ ]:
x=np.ones((10,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
x=x.reshape(2,25)
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.]])