<a href="https://colab.research.google.com/github/diaJalaeyRakhna/numpy-assigns/blob/main/PIAIC52062_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr1 = np.arange(10)        # 1D array with elements 0-9
arr1 = arr1.reshape(2, 5)   # convert to 2D array
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# use arr1 from Question1
arr2 = np.ones((2, 5), dtype=int)
np.vstack((arr1, arr2))     # vertically stack both arrays

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [24]:
# use arr1 and arr2 from prev. question
np.hstack((arr1, arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr3 = np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]])   # array of 5 arrays with 2 elements each
arr3.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [26]:
arr4 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8 , 9], [10, 11, 12, 13, 14]])    # dimension or shape = (3, 5)
np.reshape(arr4, -1)
# or simply
arr5 = arr4.reshape(-1)     # arr5 is 1D
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [27]:
arr5.reshape(5, 3)    # or arr5.reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [28]:
arr6 = np.arange(25).reshape(5, 5)
print("Input Array:\n", arr6, "\n\nSquared Array:\n", arr6 ** 2)

Input Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

Squared Array:
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [29]:
arr7 = np.arange(30).reshape(5, 6)
print("Input Array:\n", arr7, "\n\nMean of Array:")
np.mean(arr7)   # or arr7.mean()

Input Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 

Mean of Array:


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [30]:
print("Input Array:\n", arr7, "\n\nStd. Deviation of Array:")
round(np.std(arr7), 3)    # or arr7.std()

Input Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 

Std. Deviation of Array:


8.655

## Question:10

### Find the median of the previous array in Q8?

In [31]:
print("Input Array:\n", arr7, "\n\nArray Median:")
np.median(arr7)

Input Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 

Array Median:


14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [32]:
print("Input Array:\n", arr7, "\n\nArray Transpose:\n", arr7.transpose())

Input Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 

Array Transpose:
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [33]:
arr8 = np.arange(16).reshape(4, 4)
print("Input Array:\n", arr8, "\n\nSum of Diagonal Elements =", sum(np.diagonal(arr8)))      # or np.trace(arr8)

Input Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

Sum of Diagonal Elements = 30


## Question:13

### Find the determinant of the previous array in Q12?

In [34]:
print("Input Array:\n", arr8, "\n\nDeterminant of Array =", np.linalg.det(arr8))      # or np.trace(arr8)

Input Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

Determinant of Array = 0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [35]:
arr9 = np.arange(101)
print("Input Array:\n", arr9, "\n\nArray's 5th Percentile =", np.percentile(arr9, 5), "\n\t95th Percentile =", np.percentile(arr9, 95))

Input Array:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100] 

Array's 5th Percentile = 5.0 
	95th Percentile = 95.0


## Question:15

### How to find if a given array has any null values?

In [50]:
arr10 = np.random.randint(0, 50, 10)
print(arr10)
hasNull = np.any(np.isnan(arr10))
print("Array has null values: ", hasNull)

arr10 = arr10.astype(float)
arr10[7] = np.nan
print(arr10)
hasNull = np.any(np.isnan(arr10))
print("Array has null values: ", hasNull)

[49 47 20 42 28 24 31 15 10 26]
Array has null values:  False
[49. 47. 20. 42. 28. 24. 31. nan 10. 26.]
Array has null values:  True
